// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LoadBalancerRuleInitParameters struct {

	// (Number) Balancer incoming traffic TCP port
	// Balancer incoming traffic TCP port
	BalancerPort *float64 `json:"balancerPort,omitempty" tf:"balancer_port,omitempty"`

	// (String) Balancer incoming traffic protocol
	// Balancer incoming traffic protocol
	BalancerProto *string `json:"balancerProto,omitempty" tf:"balancer_proto,omitempty"`

	// (Number) ID of target balancer
	// ID of target balancer
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/lb/v1alpha1.LoadBalancer
	LBID *float64 `json:"lbId,omitempty" tf:"lb_id,omitempty"`

	// Reference to a LoadBalancer in lb to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDRef *v1.Reference `json:"lbIdRef,omitempty" tf:"-"`

	// Selector for a LoadBalancer in lb to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDSelector *v1.Selector `json:"lbIdSelector,omitempty" tf:"-"`

	// (Number) Server incoming traffic TCP port
	// Server incoming traffic TCP port
	ServerPort *float64 `json:"serverPort,omitempty" tf:"server_port,omitempty"`

	// (String) Server incoming traffic protocol
	// Server incoming traffic protocol
	ServerProto *string `json:"serverProto,omitempty" tf:"server_proto,omitempty"`
}

type LoadBalancerRuleObservation struct {

	// (Number) Balancer incoming traffic TCP port
	// Balancer incoming traffic TCP port
	BalancerPort *float64 `json:"balancerPort,omitempty" tf:"balancer_port,omitempty"`

	// (String) Balancer incoming traffic protocol
	// Balancer incoming traffic protocol
	BalancerProto *string `json:"balancerProto,omitempty" tf:"balancer_proto,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) ID of target balancer
	// ID of target balancer
	LBID *float64 `json:"lbId,omitempty" tf:"lb_id,omitempty"`

	// (Number) Server incoming traffic TCP port
	// Server incoming traffic TCP port
	ServerPort *float64 `json:"serverPort,omitempty" tf:"server_port,omitempty"`

	// (String) Server incoming traffic protocol
	// Server incoming traffic protocol
	ServerProto *string `json:"serverProto,omitempty" tf:"server_proto,omitempty"`
}

type LoadBalancerRuleParameters struct {

	// (Number) Balancer incoming traffic TCP port
	// Balancer incoming traffic TCP port
	// +kubebuilder:validation:Optional
	BalancerPort *float64 `json:"balancerPort,omitempty" tf:"balancer_port,omitempty"`

	// (String) Balancer incoming traffic protocol
	// Balancer incoming traffic protocol
	// +kubebuilder:validation:Optional
	BalancerProto *string `json:"balancerProto,omitempty" tf:"balancer_proto,omitempty"`

	// (Number) ID of target balancer
	// ID of target balancer
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/lb/v1alpha1.LoadBalancer
	// +kubebuilder:validation:Optional
	LBID *float64 `json:"lbId,omitempty" tf:"lb_id,omitempty"`

	// Reference to a LoadBalancer in lb to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDRef *v1.Reference `json:"lbIdRef,omitempty" tf:"-"`

	// Selector for a LoadBalancer in lb to populate lbId.
	// +kubebuilder:validation:Optional
	LBIDSelector *v1.Selector `json:"lbIdSelector,omitempty" tf:"-"`

	// (Number) Server incoming traffic TCP port
	// Server incoming traffic TCP port
	// +kubebuilder:validation:Optional
	ServerPort *float64 `json:"serverPort,omitempty" tf:"server_port,omitempty"`

	// (String) Server incoming traffic protocol
	// Server incoming traffic protocol
	// +kubebuilder:validation:Optional
	ServerProto *string `json:"serverProto,omitempty" tf:"server_proto,omitempty"`
}

// LoadBalancerRuleSpec defines the desired state of LoadBalancerRule
type LoadBalancerRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LoadBalancerRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerRuleInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerRuleStatus defines the observed state of LoadBalancerRule.
type LoadBalancerRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerRule is the Schema for the LoadBalancerRules API. Resource for describing needed load balancer rule and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type LoadBalancerRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.balancerPort) || (has(self.initProvider) && has(self.initProvider.balancerPort))",message="spec.forProvider.balancerPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.balancerProto) || (has(self.initProvider) && has(self.initProvider.balancerProto))",message="spec.forProvider.balancerProto is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverPort) || (has(self.initProvider) && has(self.initProvider.serverPort))",message="spec.forProvider.serverPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serverProto) || (has(self.initProvider) && has(self.initProvider.serverProto))",message="spec.forProvider.serverProto is a required parameter"
	Spec   LoadBalancerRuleSpec   `json:"spec"`
	Status LoadBalancerRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerRuleList contains a list of LoadBalancerRules
type LoadBalancerRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerRule `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerRule_Kind             = "LoadBalancerRule"
	LoadBalancerRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerRule_Kind}.String()
	LoadBalancerRule_KindAPIVersion   = LoadBalancerRule_Kind + "." + CRDGroupVersion.String()
	LoadBalancerRule_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerRule_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerRule{}, &LoadBalancerRuleList{})
}
