// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HealthCheckInitParameters struct {

	// (Number) Error requests count threshold for active backend health check
	// Error requests count threshold for active backend health check
	Fall *float64 `json:"fall,omitempty" tf:"fall,omitempty"`

	// (Number) Interval in seconds for active backend health check
	// Interval in seconds for active backend health check
	Inter *float64 `json:"inter,omitempty" tf:"inter,omitempty"`

	// (String) Path for active backend health check
	// Path for active backend health check
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) TCP port for active backend health check
	// TCP port for active backend health check
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol for active backend health check
	// Protocol for active backend health check
	Proto *string `json:"proto,omitempty" tf:"proto,omitempty"`

	// (Number) Success requests count threshold for active backend health check
	// Success requests count threshold for active backend health check
	Rise *float64 `json:"rise,omitempty" tf:"rise,omitempty"`

	// (Number) Timeout for active backend health check
	// Timeout for active backend health check
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type HealthCheckObservation struct {

	// (Number) Error requests count threshold for active backend health check
	// Error requests count threshold for active backend health check
	Fall *float64 `json:"fall,omitempty" tf:"fall,omitempty"`

	// (Number) Interval in seconds for active backend health check
	// Interval in seconds for active backend health check
	Inter *float64 `json:"inter,omitempty" tf:"inter,omitempty"`

	// (String) Path for active backend health check
	// Path for active backend health check
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) TCP port for active backend health check
	// TCP port for active backend health check
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol for active backend health check
	// Protocol for active backend health check
	Proto *string `json:"proto,omitempty" tf:"proto,omitempty"`

	// (Number) Success requests count threshold for active backend health check
	// Success requests count threshold for active backend health check
	Rise *float64 `json:"rise,omitempty" tf:"rise,omitempty"`

	// (Number) Timeout for active backend health check
	// Timeout for active backend health check
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type HealthCheckParameters struct {

	// (Number) Error requests count threshold for active backend health check
	// Error requests count threshold for active backend health check
	// +kubebuilder:validation:Optional
	Fall *float64 `json:"fall,omitempty" tf:"fall,omitempty"`

	// (Number) Interval in seconds for active backend health check
	// Interval in seconds for active backend health check
	// +kubebuilder:validation:Optional
	Inter *float64 `json:"inter,omitempty" tf:"inter,omitempty"`

	// (String) Path for active backend health check
	// Path for active backend health check
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) TCP port for active backend health check
	// TCP port for active backend health check
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Protocol for active backend health check
	// Protocol for active backend health check
	// +kubebuilder:validation:Optional
	Proto *string `json:"proto,omitempty" tf:"proto,omitempty"`

	// (Number) Success requests count threshold for active backend health check
	// Success requests count threshold for active backend health check
	// +kubebuilder:validation:Optional
	Rise *float64 `json:"rise,omitempty" tf:"rise,omitempty"`

	// (Number) Timeout for active backend health check
	// Timeout for active backend health check
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type LoadBalancerInitParameters struct {

	// (String) Algorithm for balancing
	// Algorithm for balancing
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) Availability zone for load balancer
	// Availability zone for load balancer
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Number) Client timeout
	// Client timeout
	ClientTimeout *float64 `json:"clientTimeout,omitempty" tf:"client_timeout,omitempty"`

	// (Number) Connection timeout
	// Connection timeout
	ConnectTimeout *float64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/vpc/v1alpha1.FloatingIP
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.Reference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.Selector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// (Block List, Max: 1) (see below for nested schema)
	HealthCheck []HealthCheckInitParameters `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// (Number) Http request timeout
	// Http request timeout
	HttprequestTimeout *float64 `json:"httprequestTimeout,omitempty" tf:"httprequest_timeout,omitempty"`

	// (Set of String) Backends IPs
	// Backends IPs
	// +listType=set
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (Boolean) Keep alive connection from balancer to backend server
	// Keep alive connection from balancer to backend server
	IsKeepalive *bool `json:"isKeepalive,omitempty" tf:"is_keepalive,omitempty"`

	// (Boolean) Automatic redirect HTTP to HTTPS
	// Automatic redirect HTTP to HTTPS
	IsSSL *bool `json:"isSsl,omitempty" tf:"is_ssl,omitempty"`

	// (Boolean) Save user session for balancing to same backend server
	// Save user session for balancing to same backend server
	IsSticky *bool `json:"isSticky,omitempty" tf:"is_sticky,omitempty"`

	// protocol for communicating with backend server
	// Use PROXY-protocol for communicating with backend server
	IsUseProxy *bool `json:"isUseProxy,omitempty" tf:"is_use_proxy,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for load balancer (see below for nested schema)
	// Flag that enables local network for load balancer
	LocalNetwork []LocalNetworkInitParameters `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// (Number) Maximum number of connections to backend server
	// Maximum number of connections to backend server
	Maxconn *float64 `json:"maxconn,omitempty" tf:"maxconn,omitempty"`

	// (String) Name for balancer
	// Name for balancer
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Preset ID for balancer
	// Preset ID for balancer
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created balancer
	// Project ID for created balancer
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Server timeout
	// Server timeout
	ServerTimeout *float64 `json:"serverTimeout,omitempty" tf:"server_timeout,omitempty"`
}

type LoadBalancerObservation struct {

	// (String) Algorithm for balancing
	// Algorithm for balancing
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) Availability zone for load balancer
	// Availability zone for load balancer
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Number) Client timeout
	// Client timeout
	ClientTimeout *float64 `json:"clientTimeout,omitempty" tf:"client_timeout,omitempty"`

	// (Number) Connection timeout
	// Connection timeout
	ConnectTimeout *float64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	HealthCheck []HealthCheckObservation `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// (Number) Http request timeout
	// Http request timeout
	HttprequestTimeout *float64 `json:"httprequestTimeout,omitempty" tf:"httprequest_timeout,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// address balancer of network interface
	// IP-address balancer of network interface
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Set of String) Backends IPs
	// Backends IPs
	// +listType=set
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (Boolean) Keep alive connection from balancer to backend server
	// Keep alive connection from balancer to backend server
	IsKeepalive *bool `json:"isKeepalive,omitempty" tf:"is_keepalive,omitempty"`

	// (Boolean) Automatic redirect HTTP to HTTPS
	// Automatic redirect HTTP to HTTPS
	IsSSL *bool `json:"isSsl,omitempty" tf:"is_ssl,omitempty"`

	// (Boolean) Save user session for balancing to same backend server
	// Save user session for balancing to same backend server
	IsSticky *bool `json:"isSticky,omitempty" tf:"is_sticky,omitempty"`

	// protocol for communicating with backend server
	// Use PROXY-protocol for communicating with backend server
	IsUseProxy *bool `json:"isUseProxy,omitempty" tf:"is_use_proxy,omitempty"`

	// address balancer of network interface
	// Local IP-address balancer of network interface
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for load balancer (see below for nested schema)
	// Flag that enables local network for load balancer
	LocalNetwork []LocalNetworkObservation `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// (Number) Maximum number of connections to backend server
	// Maximum number of connections to backend server
	Maxconn *float64 `json:"maxconn,omitempty" tf:"maxconn,omitempty"`

	// (String) Name for balancer
	// Name for balancer
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Preset ID for balancer
	// Preset ID for balancer
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created balancer
	// Project ID for created balancer
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Server timeout
	// Server timeout
	ServerTimeout *float64 `json:"serverTimeout,omitempty" tf:"server_timeout,omitempty"`

	// (String) Current status of balancer (started, starting, stoped, no_paid)
	// Current status of balancer (`started`, `starting`, `stoped`, `no_paid`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type LoadBalancerParameters struct {

	// (String) Algorithm for balancing
	// Algorithm for balancing
	// +kubebuilder:validation:Optional
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) Availability zone for load balancer
	// Availability zone for load balancer
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Number) Client timeout
	// Client timeout
	// +kubebuilder:validation:Optional
	ClientTimeout *float64 `json:"clientTimeout,omitempty" tf:"client_timeout,omitempty"`

	// (Number) Connection timeout
	// Connection timeout
	// +kubebuilder:validation:Optional
	ConnectTimeout *float64 `json:"connectTimeout,omitempty" tf:"connect_timeout,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/vpc/v1alpha1.FloatingIP
	// +kubebuilder:validation:Optional
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.Reference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.Selector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	HealthCheck []HealthCheckParameters `json:"healthCheck,omitempty" tf:"health_check,omitempty"`

	// (Number) Http request timeout
	// Http request timeout
	// +kubebuilder:validation:Optional
	HttprequestTimeout *float64 `json:"httprequestTimeout,omitempty" tf:"httprequest_timeout,omitempty"`

	// (Set of String) Backends IPs
	// Backends IPs
	// +kubebuilder:validation:Optional
	// +listType=set
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (Boolean) Keep alive connection from balancer to backend server
	// Keep alive connection from balancer to backend server
	// +kubebuilder:validation:Optional
	IsKeepalive *bool `json:"isKeepalive,omitempty" tf:"is_keepalive,omitempty"`

	// (Boolean) Automatic redirect HTTP to HTTPS
	// Automatic redirect HTTP to HTTPS
	// +kubebuilder:validation:Optional
	IsSSL *bool `json:"isSsl,omitempty" tf:"is_ssl,omitempty"`

	// (Boolean) Save user session for balancing to same backend server
	// Save user session for balancing to same backend server
	// +kubebuilder:validation:Optional
	IsSticky *bool `json:"isSticky,omitempty" tf:"is_sticky,omitempty"`

	// protocol for communicating with backend server
	// Use PROXY-protocol for communicating with backend server
	// +kubebuilder:validation:Optional
	IsUseProxy *bool `json:"isUseProxy,omitempty" tf:"is_use_proxy,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for load balancer (see below for nested schema)
	// Flag that enables local network for load balancer
	// +kubebuilder:validation:Optional
	LocalNetwork []LocalNetworkParameters `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// (Number) Maximum number of connections to backend server
	// Maximum number of connections to backend server
	// +kubebuilder:validation:Optional
	Maxconn *float64 `json:"maxconn,omitempty" tf:"maxconn,omitempty"`

	// (String) Name for balancer
	// Name for balancer
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Preset ID for balancer
	// Preset ID for balancer
	// +kubebuilder:validation:Optional
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created balancer
	// Project ID for created balancer
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Server timeout
	// Server timeout
	// +kubebuilder:validation:Optional
	ServerTimeout *float64 `json:"serverTimeout,omitempty" tf:"server_timeout,omitempty"`
}

type LocalNetworkInitParameters struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// address balancer of network interface
	// Address in VPC subnetwork for manual assign
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type LocalNetworkObservation struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// address balancer of network interface
	// Address in VPC subnetwork for manual assign
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type LocalNetworkParameters struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// address balancer of network interface
	// Address in VPC subnetwork for manual assign
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

// LoadBalancerSpec defines the desired state of LoadBalancer
type LoadBalancerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LoadBalancerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerStatus defines the observed state of LoadBalancer.
type LoadBalancerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancer is the Schema for the LoadBalancers API. Resource for describing needed load balancer and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type LoadBalancer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.presetId) || (has(self.initProvider) && has(self.initProvider.presetId))",message="spec.forProvider.presetId is a required parameter"
	Spec   LoadBalancerSpec   `json:"spec"`
	Status LoadBalancerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerList contains a list of LoadBalancers
type LoadBalancerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancer `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancer_Kind             = "LoadBalancer"
	LoadBalancer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancer_Kind}.String()
	LoadBalancer_KindAPIVersion   = LoadBalancer_Kind + "." + CRDGroupVersion.String()
	LoadBalancer_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancer_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancer{}, &LoadBalancerList{})
}
