// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BucketSubdomainInitParameters struct {

	// (Number) S3 Bucket ID for which file should be created
	// S3 Bucket ID for which file should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/s3/v1alpha1.Bucket
	BucketID *float64 `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// Reference to a Bucket in s3 to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDRef *v1.NamespacedReference `json:"bucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in s3 to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDSelector *v1.NamespacedSelector `json:"bucketIdSelector,omitempty" tf:"-"`

	// (Boolean) Flag that ensures releasing SSL certificate for subdomain
	// Flag that ensures releasing SSL certificate for subdomain
	ReleaseCert *bool `json:"releaseCert,omitempty" tf:"release_cert,omitempty"`

	// (String) Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to s3.timeweb.com
	// Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to `s3.timeweb.com`
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`
}

type BucketSubdomainObservation struct {

	// (Number) S3 Bucket ID for which file should be created
	// S3 Bucket ID for which file should be created
	BucketID *float64 `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag that ensures releasing SSL certificate for subdomain
	// Flag that ensures releasing SSL certificate for subdomain
	ReleaseCert *bool `json:"releaseCert,omitempty" tf:"release_cert,omitempty"`

	// (String) Subdomain status (ssl_released, ssl_not_requested, ssl_re_release_error)
	// Subdomain status (`ssl_released`, `ssl_not_requested`, `ssl_re_release_error`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to s3.timeweb.com
	// Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to `s3.timeweb.com`
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`
}

type BucketSubdomainParameters struct {

	// (Number) S3 Bucket ID for which file should be created
	// S3 Bucket ID for which file should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/s3/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	BucketID *float64 `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// Reference to a Bucket in s3 to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDRef *v1.NamespacedReference `json:"bucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in s3 to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDSelector *v1.NamespacedSelector `json:"bucketIdSelector,omitempty" tf:"-"`

	// (Boolean) Flag that ensures releasing SSL certificate for subdomain
	// Flag that ensures releasing SSL certificate for subdomain
	// +kubebuilder:validation:Optional
	ReleaseCert *bool `json:"releaseCert,omitempty" tf:"release_cert,omitempty"`

	// (String) Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to s3.timeweb.com
	// Subdomain for serving files from S3 bucket. Subdomain should be valid domain name (and unique between buckets) with CNAME record that pointing to `s3.timeweb.com`
	// +kubebuilder:validation:Optional
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`
}

// BucketSubdomainSpec defines the desired state of BucketSubdomain
type BucketSubdomainSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BucketSubdomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketSubdomainInitParameters `json:"initProvider,omitempty"`
}

// BucketSubdomainStatus defines the observed state of BucketSubdomain.
type BucketSubdomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketSubdomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BucketSubdomain is the Schema for the BucketSubdomains API. Resource for add needed subdomain to S3 bucket
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type BucketSubdomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subdomain) || (has(self.initProvider) && has(self.initProvider.subdomain))",message="spec.forProvider.subdomain is a required parameter"
	Spec   BucketSubdomainSpec   `json:"spec"`
	Status BucketSubdomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketSubdomainList contains a list of BucketSubdomains
type BucketSubdomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketSubdomain `json:"items"`
}

// Repository type metadata.
var (
	BucketSubdomain_Kind             = "BucketSubdomain"
	BucketSubdomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketSubdomain_Kind}.String()
	BucketSubdomain_KindAPIVersion   = BucketSubdomain_Kind + "." + CRDGroupVersion.String()
	BucketSubdomain_GroupVersionKind = CRDGroupVersion.WithKind(BucketSubdomain_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketSubdomain{}, &BucketSubdomainList{})
}
