apiVersion: vpc.timeweb.m.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: example-vpc
  name: example-vpc
  namespace: crossplane-system
spec:
  forProvider:
    description: Some example VPC
    location: ru-1
    name: Example VPC
    subnetV4: 192.168.0.0/24

---

apiVersion: database.timeweb.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: example-redis-7
  name: example-redis-7
  namespace: crossplane-system
spec:
  forProvider:
    name: example_redis7
    network:
    - id: ${twc_vpc.example-vpc.id}
    presetId: ${data.twc_database_preset.example-db-preset-redis-7.id}
    type: redis7

---

apiVersion: lb.timeweb.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: example-lb
  name: example-lb
  namespace: crossplane-system
spec:
  forProvider:
    algo: roundrobin
    healthCheck:
    - fall: 3
      inter: 10
      path: /lala
      port: 80
      proto: http
      rise: 2
      timeout: 5
    ips: []
    isKeepalive: false
    isSsl: false
    isSticky: false
    isUseProxy: false
    localNetwork:
    - id: ${twc_vpc.example-vpc.id}
      ip: 192.168.0.20
    name: example-lb
    presetId: ${data.twc_lb_preset.example-lb-preset.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: twc_project

---

apiVersion: server.timeweb.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: example-server-with-local-network
  name: example-server-with-local-network
  namespace: crossplane-system
spec:
  forProvider:
    localNetwork:
    - id: ${twc_vpc.example-vpc.id}
    name: Example server with local network
    osId: ${data.twc_os.example-os.id}
    presetId: ${data.twc_presets.example-preset.id}

---

apiVersion: server.timeweb.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: example-server-with-local-network-and-address
  name: example-server-with-local-network-and-address
  namespace: crossplane-system
spec:
  forProvider:
    localNetwork:
    - id: ${twc_vpc.example-vpc.id}
      ip: 192.168.0.15
    name: Example server with local network and address
    osId: ${data.twc_os.example-os.id}
    presetId: ${data.twc_presets.example-preset.id}
