// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FirewallInitParameters struct {

	// (String) Description for firewall
	// Description for firewall
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set) (see below for nested schema)
	Link []LinkInitParameters `json:"link,omitempty" tf:"link,omitempty"`

	// (String) Name for firewall
	// Name for firewall
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FirewallObservation struct {

	// (String) Description for firewall
	// Description for firewall
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) (see below for nested schema)
	Link []LinkObservation `json:"link,omitempty" tf:"link,omitempty"`

	// (String) Name for firewall
	// Name for firewall
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FirewallParameters struct {

	// (String) Description for firewall
	// Description for firewall
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Link []LinkParameters `json:"link,omitempty" tf:"link,omitempty"`

	// (String) Name for firewall
	// Name for firewall
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LinkInitParameters struct {

	// (String) The ID of this resource.
	// Resource ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Resource type [server, dbaas, balancer]
	// Resource type [server, dbaas, balancer]
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LinkObservation struct {

	// (String) The ID of this resource.
	// Resource ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Resource type [server, dbaas, balancer]
	// Resource type [server, dbaas, balancer]
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LinkParameters struct {

	// (String) The ID of this resource.
	// Resource ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Resource type [server, dbaas, balancer]
	// Resource type [server, dbaas, balancer]
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// FirewallSpec defines the desired state of Firewall
type FirewallSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FirewallParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallInitParameters `json:"initProvider,omitempty"`
}

// FirewallStatus defines the observed state of Firewall.
type FirewallStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Firewall is the Schema for the Firewalls API. Resource for describing needed firewall and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type Firewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FirewallSpec   `json:"spec"`
	Status FirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallList contains a list of Firewalls
type FirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Firewall `json:"items"`
}

// Repository type metadata.
var (
	Firewall_Kind             = "Firewall"
	Firewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Firewall_Kind}.String()
	Firewall_KindAPIVersion   = Firewall_Kind + "." + CRDGroupVersion.String()
	Firewall_GroupVersionKind = CRDGroupVersion.WithKind(Firewall_Kind)
)

func init() {
	SchemeBuilder.Register(&Firewall{}, &FirewallList{})
}
