// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Rule.
func (mg *Rule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FirewallID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FirewallIDRef,
		Selector:     mg.Spec.ForProvider.FirewallIDSelector,
		To: reference.To{
			List:    &FirewallList{},
			Managed: &Firewall{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FirewallID")
	}
	mg.Spec.ForProvider.FirewallID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FirewallIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FirewallID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FirewallIDRef,
		Selector:     mg.Spec.InitProvider.FirewallIDSelector,
		To: reference.To{
			List:    &FirewallList{},
			Managed: &Firewall{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FirewallID")
	}
	mg.Spec.InitProvider.FirewallID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FirewallIDRef = rsp.ResolvedReference

	return nil
}
