// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserInitParameters struct {

	// (Number) Database cluster ID for which user be created
	// Database cluster ID for which user be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/database/v1alpha1.Cluster
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Description for user
	// Description for user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Allowed host for login as this user
	// Allowed host for login as this user
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Block List) Privileges of user by instance (see below for nested schema)
	// Privileges of user by instance
	Instance []UserInstanceInitParameters `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Login for user
	// Login for user
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String, Sensitive) Password for user
	// Password for user
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (List of String) Privileges of user
	// Privileges of user
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

type UserInstanceInitParameters struct {

	// (Number) Database instance ID for which user has privileges
	// Database instance ID for which user has privileges
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (List of String) Privileges of user
	// Privileges of user
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

type UserInstanceObservation struct {

	// (Number) Database instance ID for which user has privileges
	// Database instance ID for which user has privileges
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (List of String) Privileges of user
	// Privileges of user
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

type UserInstanceParameters struct {

	// (Number) Database instance ID for which user has privileges
	// Database instance ID for which user has privileges
	// +kubebuilder:validation:Optional
	InstanceID *float64 `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (List of String) Privileges of user
	// Privileges of user
	// +kubebuilder:validation:Optional
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

type UserObservation struct {

	// (Number) Database cluster ID for which user be created
	// Database cluster ID for which user be created
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) Description for user
	// Description for user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Allowed host for login as this user
	// Allowed host for login as this user
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List) Privileges of user by instance (see below for nested schema)
	// Privileges of user by instance
	Instance []UserInstanceObservation `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Login for user
	// Login for user
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (List of String) Privileges of user
	// Privileges of user
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

type UserParameters struct {

	// (Number) Database cluster ID for which user be created
	// Database cluster ID for which user be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/database/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) Description for user
	// Description for user
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Allowed host for login as this user
	// Allowed host for login as this user
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Block List) Privileges of user by instance (see below for nested schema)
	// Privileges of user by instance
	// +kubebuilder:validation:Optional
	Instance []UserInstanceParameters `json:"instance,omitempty" tf:"instance,omitempty"`

	// (String) Login for user
	// Login for user
	// +kubebuilder:validation:Optional
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// (String, Sensitive) Password for user
	// Password for user
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (List of String) Privileges of user
	// Privileges of user
	// +kubebuilder:validation:Optional
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Resource for describing needed database user and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.login) || (has(self.initProvider) && has(self.initProvider.login))",message="spec.forProvider.login is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
