// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Router.
func (mg *Router) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Ips); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ips[i3].IP),
			Extract:      resource.ExtractParamPath("ip", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Ips[i3].IPRef,
			Selector:     mg.Spec.ForProvider.Ips[i3].IPSelector,
			To: reference.To{
				List:    &FloatingIPList{},
				Managed: &FloatingIP{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Ips[i3].IP")
		}
		mg.Spec.ForProvider.Ips[i3].IP = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Ips[i3].IPRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Ips); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.Ips[i3].NAT); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkName),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkNameRef,
				Selector:     mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkNameSelector,
				To: reference.To{
					List:    &VPCList{},
					Managed: &VPC{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkName")
			}
			mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkName = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Ips[i3].NAT[i4].NetworkNameRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Networks); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Networks[i3].NetworkName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Networks[i3].NetworkNameRef,
			Selector:     mg.Spec.ForProvider.Networks[i3].NetworkNameSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Networks[i3].NetworkName")
		}
		mg.Spec.ForProvider.Networks[i3].NetworkName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Networks[i3].NetworkNameRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Ips); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Ips[i3].IP),
			Extract:      resource.ExtractParamPath("ip", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Ips[i3].IPRef,
			Selector:     mg.Spec.InitProvider.Ips[i3].IPSelector,
			To: reference.To{
				List:    &FloatingIPList{},
				Managed: &FloatingIP{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Ips[i3].IP")
		}
		mg.Spec.InitProvider.Ips[i3].IP = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Ips[i3].IPRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Ips); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.Ips[i3].NAT); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkName),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkNameRef,
				Selector:     mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkNameSelector,
				To: reference.To{
					List:    &VPCList{},
					Managed: &VPC{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkName")
			}
			mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkName = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Ips[i3].NAT[i4].NetworkNameRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Networks); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Networks[i3].NetworkName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Networks[i3].NetworkNameRef,
			Selector:     mg.Spec.InitProvider.Networks[i3].NetworkNameSelector,
			To: reference.To{
				List:    &VPCList{},
				Managed: &VPC{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Networks[i3].NetworkName")
		}
		mg.Spec.InitProvider.Networks[i3].NetworkName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Networks[i3].NetworkNameRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.ProjectID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ProjectIDRef,
		Selector:     mg.Spec.InitProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	return nil
}
