// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FloatingIPInitParameters struct {

	// (String) Address of specified floating IP Address
	// Address of specified floating IP Address
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Comment of specified floating IP Address
	// Comment of specified floating IP Address
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Enabled DDoS Guard for specified floating IP Address
	// Enabled DDoS Guard for specified floating IP Address
	DdosGuard *bool `json:"ddosGuard,omitempty" tf:"ddos_guard,omitempty"`

	// (String) PTR record in DNS zone of specified floating IP Address
	// PTR record in DNS zone of specified floating IP Address
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Block List, Max: 1) Address of specified floating IP Address (see below for nested schema)
	// Address of specified floating IP Address
	Resource []ResourceInitParameters `json:"resource,omitempty" tf:"resource,omitempty"`
}

type FloatingIPObservation struct {

	// (String) Address of specified floating IP Address
	// Address of specified floating IP Address
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Comment of specified floating IP Address
	// Comment of specified floating IP Address
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Enabled DDoS Guard for specified floating IP Address
	// Enabled DDoS Guard for specified floating IP Address
	DdosGuard *bool `json:"ddosGuard,omitempty" tf:"ddos_guard,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Address of specified floating IP Address
	// Address of specified floating IP Address
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) PTR record in DNS zone of specified floating IP Address
	// PTR record in DNS zone of specified floating IP Address
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Block List, Max: 1) Address of specified floating IP Address (see below for nested schema)
	// Address of specified floating IP Address
	Resource []ResourceObservation `json:"resource,omitempty" tf:"resource,omitempty"`
}

type FloatingIPParameters struct {

	// (String) Address of specified floating IP Address
	// Address of specified floating IP Address
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Comment of specified floating IP Address
	// Comment of specified floating IP Address
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) Enabled DDoS Guard for specified floating IP Address
	// Enabled DDoS Guard for specified floating IP Address
	// +kubebuilder:validation:Optional
	DdosGuard *bool `json:"ddosGuard,omitempty" tf:"ddos_guard,omitempty"`

	// (String) PTR record in DNS zone of specified floating IP Address
	// PTR record in DNS zone of specified floating IP Address
	// +kubebuilder:validation:Optional
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Block List, Max: 1) Address of specified floating IP Address (see below for nested schema)
	// Address of specified floating IP Address
	// +kubebuilder:validation:Optional
	Resource []ResourceParameters `json:"resource,omitempty" tf:"resource,omitempty"`
}

type ResourceInitParameters struct {

	// (String) The ID of this resource.
	// ID of resource that bind with floating IP Address
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Type of resource that bind with floating IP Address (server, balancer, dbaas)
	// Type of resource that bind with floating IP Address (`server`, `balancer`, `dbaas`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ResourceObservation struct {

	// (String) The ID of this resource.
	// ID of resource that bind with floating IP Address
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Type of resource that bind with floating IP Address (server, balancer, dbaas)
	// Type of resource that bind with floating IP Address (`server`, `balancer`, `dbaas`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ResourceParameters struct {

	// (String) The ID of this resource.
	// ID of resource that bind with floating IP Address
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Type of resource that bind with floating IP Address (server, balancer, dbaas)
	// Type of resource that bind with floating IP Address (`server`, `balancer`, `dbaas`)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// FloatingIPSpec defines the desired state of FloatingIP
type FloatingIPSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FloatingIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FloatingIPInitParameters `json:"initProvider,omitempty"`
}

// FloatingIPStatus defines the observed state of FloatingIP.
type FloatingIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FloatingIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FloatingIP is the Schema for the FloatingIPs API. Resource for describing needed floating IP and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type FloatingIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.availabilityZone) || (has(self.initProvider) && has(self.initProvider.availabilityZone))",message="spec.forProvider.availabilityZone is a required parameter"
	Spec   FloatingIPSpec   `json:"spec"`
	Status FloatingIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FloatingIPList contains a list of FloatingIPs
type FloatingIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FloatingIP `json:"items"`
}

// Repository type metadata.
var (
	FloatingIP_Kind             = "FloatingIP"
	FloatingIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FloatingIP_Kind}.String()
	FloatingIP_KindAPIVersion   = FloatingIP_Kind + "." + CRDGroupVersion.String()
	FloatingIP_GroupVersionKind = CRDGroupVersion.WithKind(FloatingIP_Kind)
)

func init() {
	SchemeBuilder.Register(&FloatingIP{}, &FloatingIPList{})
}
