// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DiskInitParameters struct {

	// (Number) Disk size for created disk in MB, minimal size is 5120, step is 5120
	// Disk size for created disk in MB, minimal size is `5120`, step is `5120`
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number) Server ID for which disk should be created
	// Server ID for which disk should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

type DiskObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag that shows current mount status of disk
	// Flag that shows current mount status of disk
	IsMounted *bool `json:"isMounted,omitempty" tf:"is_mounted,omitempty"`

	// (Boolean) Flag that shows disk is system or not (always false for now)
	// Flag that shows disk is system or not (always `false` for now)
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// (Number) Disk size for created disk in MB, minimal size is 5120, step is 5120
	// Disk size for created disk in MB, minimal size is `5120`, step is `5120`
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number) Server ID for which disk should be created
	// Server ID for which disk should be created
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// (String) Current status of disk
	// Current status of disk
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The name of the disk it was mounted on
	// The name of the disk it was mounted on
	SystemName *string `json:"systemName,omitempty" tf:"system_name,omitempty"`

	// (String) Disk type (ssd, nvme, hdd)
	// Disk type (`ssd`, `nvme`, `hdd`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Number) Used disk space in MB
	// Used disk space in MB
	Used *float64 `json:"used,omitempty" tf:"used,omitempty"`
}

type DiskParameters struct {

	// (Number) Disk size for created disk in MB, minimal size is 5120, step is 5120
	// Disk size for created disk in MB, minimal size is `5120`, step is `5120`
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number) Server ID for which disk should be created
	// Server ID for which disk should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

// DiskSpec defines the desired state of Disk
type DiskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DiskParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DiskInitParameters `json:"initProvider,omitempty"`
}

// DiskStatus defines the observed state of Disk.
type DiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DiskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Disk is the Schema for the Disks API. Resource for describing needed additional disk for server and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type Disk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	Spec   DiskSpec   `json:"spec"`
	Status DiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskList contains a list of Disks
type DiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Disk `json:"items"`
}

// Repository type metadata.
var (
	Disk_Kind             = "Disk"
	Disk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Disk_Kind}.String()
	Disk_KindAPIVersion   = Disk_Kind + "." + CRDGroupVersion.String()
	Disk_GroupVersionKind = CRDGroupVersion.WithKind(Disk_Kind)
)

func init() {
	SchemeBuilder.Register(&Disk{}, &DiskList{})
}
