// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DiskBackupScheduleInitParameters struct {

	// (Number) Maximum stored copy count
	// Maximum stored copy count
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// (String) Creation date for first backup
	// Creation date for first backup
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// (Number) Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Boolean) Enable auto backups
	// Enable auto backups
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Interval between auto backups
	// Interval between auto backups
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (Number) Disk ID for which backup should be configured
	// Disk ID for which backup should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Disk
	SourceServerDiskID *float64 `json:"sourceServerDiskId,omitempty" tf:"source_server_disk_id,omitempty"`

	// Reference to a Disk in server to populate sourceServerDiskId.
	// +kubebuilder:validation:Optional
	SourceServerDiskIDRef *v1.Reference `json:"sourceServerDiskIdRef,omitempty" tf:"-"`

	// Selector for a Disk in server to populate sourceServerDiskId.
	// +kubebuilder:validation:Optional
	SourceServerDiskIDSelector *v1.Selector `json:"sourceServerDiskIdSelector,omitempty" tf:"-"`

	// (Number) Server ID for which disk auto backups should be configured
	// Server ID for which disk auto backups should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

type DiskBackupScheduleObservation struct {

	// (Number) Maximum stored copy count
	// Maximum stored copy count
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// (String) Creation date for first backup
	// Creation date for first backup
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// (Number) Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Boolean) Enable auto backups
	// Enable auto backups
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Interval between auto backups
	// Interval between auto backups
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (Number) Disk ID for which backup should be configured
	// Disk ID for which backup should be configured
	SourceServerDiskID *float64 `json:"sourceServerDiskId,omitempty" tf:"source_server_disk_id,omitempty"`

	// (Number) Server ID for which disk auto backups should be configured
	// Server ID for which disk auto backups should be configured
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`
}

type DiskBackupScheduleParameters struct {

	// (Number) Maximum stored copy count
	// Maximum stored copy count
	// +kubebuilder:validation:Optional
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// (String) Creation date for first backup
	// Creation date for first backup
	// +kubebuilder:validation:Optional
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// (Number) Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	// +kubebuilder:validation:Optional
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Boolean) Enable auto backups
	// Enable auto backups
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Interval between auto backups
	// Interval between auto backups
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// (Number) Disk ID for which backup should be configured
	// Disk ID for which backup should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Disk
	// +kubebuilder:validation:Optional
	SourceServerDiskID *float64 `json:"sourceServerDiskId,omitempty" tf:"source_server_disk_id,omitempty"`

	// Reference to a Disk in server to populate sourceServerDiskId.
	// +kubebuilder:validation:Optional
	SourceServerDiskIDRef *v1.Reference `json:"sourceServerDiskIdRef,omitempty" tf:"-"`

	// Selector for a Disk in server to populate sourceServerDiskId.
	// +kubebuilder:validation:Optional
	SourceServerDiskIDSelector *v1.Selector `json:"sourceServerDiskIdSelector,omitempty" tf:"-"`

	// (Number) Server ID for which disk auto backups should be configured
	// Server ID for which disk auto backups should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

// DiskBackupScheduleSpec defines the desired state of DiskBackupSchedule
type DiskBackupScheduleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DiskBackupScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DiskBackupScheduleInitParameters `json:"initProvider,omitempty"`
}

// DiskBackupScheduleStatus defines the observed state of DiskBackupSchedule.
type DiskBackupScheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DiskBackupScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DiskBackupSchedule is the Schema for the DiskBackupSchedules API. Resource for describing needed disk auto backup properties and schedule
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type DiskBackupSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.copyCount) || (has(self.initProvider) && has(self.initProvider.copyCount))",message="spec.forProvider.copyCount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.creationStartAt) || (has(self.initProvider) && has(self.initProvider.creationStartAt))",message="spec.forProvider.creationStartAt is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	Spec   DiskBackupScheduleSpec   `json:"spec"`
	Status DiskBackupScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskBackupScheduleList contains a list of DiskBackupSchedules
type DiskBackupScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DiskBackupSchedule `json:"items"`
}

// Repository type metadata.
var (
	DiskBackupSchedule_Kind             = "DiskBackupSchedule"
	DiskBackupSchedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DiskBackupSchedule_Kind}.String()
	DiskBackupSchedule_KindAPIVersion   = DiskBackupSchedule_Kind + "." + CRDGroupVersion.String()
	DiskBackupSchedule_GroupVersionKind = CRDGroupVersion.WithKind(DiskBackupSchedule_Kind)
)

func init() {
	SchemeBuilder.Register(&DiskBackupSchedule{}, &DiskBackupScheduleList{})
}
