// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConfigurationInitParameters struct {

	// (Number) Current CPUs count of server
	// CPU count for created server
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (Number) Configurator identifier
	// Configurator ID for created server
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Disk size for created server
	// Disk size for created server
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`

	// (Number) GPU count for created server
	// GPU count for created server
	Gpu *float64 `json:"gpu,omitempty" tf:"gpu,omitempty"`

	// (Number) Current RAM size of server
	// RAM size for created server (must be divisible by 1024 and corresponds OS, software and configurator requirements)
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`
}

type ConfigurationObservation struct {

	// (Number) Current CPUs count of server
	// CPU count for created server
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (Number) Configurator identifier
	// Configurator ID for created server
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Disk size for created server
	// Disk size for created server
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`

	// (Number) GPU count for created server
	// GPU count for created server
	Gpu *float64 `json:"gpu,omitempty" tf:"gpu,omitempty"`

	// (Number) Current RAM size of server
	// RAM size for created server (must be divisible by 1024 and corresponds OS, software and configurator requirements)
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`
}

type ConfigurationParameters struct {

	// (Number) Current CPUs count of server
	// CPU count for created server
	// +kubebuilder:validation:Optional
	CPU *float64 `json:"cpu" tf:"cpu,omitempty"`

	// (Number) Configurator identifier
	// Configurator ID for created server
	// +kubebuilder:validation:Optional
	ConfiguratorID *float64 `json:"configuratorId" tf:"configurator_id,omitempty"`

	// (Number) Disk size for created server
	// Disk size for created server
	// +kubebuilder:validation:Optional
	Disk *float64 `json:"disk" tf:"disk,omitempty"`

	// (Number) GPU count for created server
	// GPU count for created server
	// +kubebuilder:validation:Optional
	Gpu *float64 `json:"gpu,omitempty" tf:"gpu,omitempty"`

	// (Number) Current RAM size of server
	// RAM size for created server (must be divisible by 1024 and corresponds OS, software and configurator requirements)
	// +kubebuilder:validation:Optional
	RAM *float64 `json:"ram" tf:"ram,omitempty"`
}

type DisksInitParameters struct {
}

type DisksObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsMounted *bool `json:"isMounted,omitempty" tf:"is_mounted,omitempty"`

	// (Boolean)
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// (Number)
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) Current status of server (installing, software_install, reinstalling, on, off, turning_on, turning_off, hard_turning_off, rebooting, hard_rebooting, removing, removed, cloning, transfer, blocked, configuring, no_paid, permanent_blocked)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String)
	SystemName *string `json:"systemName,omitempty" tf:"system_name,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Number)
	Used *float64 `json:"used,omitempty" tf:"used,omitempty"`
}

type DisksParameters struct {
}

type IpsInitParameters struct {
}

type IpsObservation struct {

	// (String) Address in VPC subnetwork for manual assign
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Boolean)
	IsMain *bool `json:"isMain,omitempty" tf:"is_main,omitempty"`

	// (String)
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IpsParameters struct {
}

type LocalNetworkInitParameters struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Address in VPC subnetwork for manual assign
	// Address in VPC subnetwork for manual assign
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// egress and ingress traffic allowed, snat - only egress traffic allowed, no_nat - only local network traffic allowed)
	// NAT mode for created servers (`dnat_and_snat` - egress and ingress traffic allowed, `snat` - only egress traffic allowed, `no_nat` - only local network traffic allowed)
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type LocalNetworkObservation struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Address in VPC subnetwork for manual assign
	// Address in VPC subnetwork for manual assign
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// egress and ingress traffic allowed, snat - only egress traffic allowed, no_nat - only local network traffic allowed)
	// NAT mode for created servers (`dnat_and_snat` - egress and ingress traffic allowed, `snat` - only egress traffic allowed, `no_nat` - only local network traffic allowed)
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type LocalNetworkParameters struct {

	// (String) The ID of this resource.
	// ID of VPC for assign address from
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Address in VPC subnetwork for manual assign
	// Address in VPC subnetwork for manual assign
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// egress and ingress traffic allowed, snat - only egress traffic allowed, no_nat - only local network traffic allowed)
	// NAT mode for created servers (`dnat_and_snat` - egress and ingress traffic allowed, `snat` - only egress traffic allowed, `no_nat` - only local network traffic allowed)
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type NetworksInitParameters struct {
}

type NetworksObservation struct {

	// (Number) Bandwidth for server
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// (List of Object) (see below for nested schema)
	Ips []IpsObservation `json:"ips,omitempty" tf:"ips,omitempty"`

	// (Boolean) Flag that shows status of DDoS guard service
	IsDdosGuard *bool `json:"isDdosGuard,omitempty" tf:"is_ddos_guard,omitempty"`

	// (String)
	NATMode *string `json:"natMode,omitempty" tf:"nat_mode,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworksParameters struct {
}

type OsInitParameters struct {
}

type OsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name for server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type OsParameters struct {
}

type ServerInitParameters struct {

	// 1, spb-3, 'spb-4', msk-1, nsk-1, 'ams-1', 'fra-1', 'ala-1')
	// Availability zone for server (`spb-1`, `spb-3`, 'spb-4', `msk-1`, `nsk-1`, 'ams-1', 'fra-1', 'ala-1')
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Number) Bandwidth for server
	// Bandwidth for server
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	// Cloud-init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	CloudInit *string `json:"cloudInit,omitempty" tf:"cloud_init,omitempty"`

	// (String) Comment for server
	// Comment for server
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	Configuration []ConfigurationInitParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/vpc/v1alpha1.FloatingIP
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.Reference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.Selector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// (String) Hostname of the server
	// Hostname of the server
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Image ID for servers (not supported for cloned servers)
	// Image ID for servers (not supported for cloned servers)
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// (Boolean) Is root password required for server
	// Is root password required for server
	IsRootPasswordRequired *bool `json:"isRootPasswordRequired,omitempty" tf:"is_root_password_required,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for created server (not supported for cloned servers) (see below for nested schema)
	// Flag that enables local network for created server (not supported for cloned servers)
	LocalNetwork []LocalNetworkInitParameters `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// (String) Name for server
	// Name for server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) OS ID for server (not supported for cloned servers)
	// OS ID for server (not supported for cloned servers)
	OsID *float64 `json:"osId,omitempty" tf:"os_id,omitempty"`

	// (Number) Preset ID for server (conflicts with configuration)
	// Preset ID for server (conflicts with configuration)
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created server
	// Project ID for created server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of Number) List of SSH keys IDs for server
	// List of SSH keys IDs for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/ssh/v1alpha1.SSHKey
	// +listType=set
	SSHKeysIds []*float64 `json:"sshKeysIds,omitempty" tf:"ssh_keys_ids,omitempty"`

	// References to SSHKey in ssh to populate sshKeysIds.
	// +kubebuilder:validation:Optional
	SSHKeysIdsRefs []v1.Reference `json:"sshKeysIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SSHKey in ssh to populate sshKeysIds.
	// +kubebuilder:validation:Optional
	SSHKeysIdsSelector *v1.Selector `json:"sshKeysIdsSelector,omitempty" tf:"-"`

	// (Number) Software ID for server (not supported for cloned servers)
	// Software ID for server (not supported for cloned servers)
	SoftwareID *float64 `json:"softwareId,omitempty" tf:"software_id,omitempty"`

	// (Number) Server ID for which clone should be created
	// Server ID for which clone should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

type ServerObservation struct {

	// 1, spb-3, 'spb-4', msk-1, nsk-1, 'ams-1', 'fra-1', 'ala-1')
	// Availability zone for server (`spb-1`, `spb-3`, 'spb-4', `msk-1`, `nsk-1`, 'ams-1', 'fra-1', 'ala-1')
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Identifier of avatar
	// Identifier of avatar
	AvatarID *string `json:"avatarId,omitempty" tf:"avatar_id,omitempty"`

	// (Number) Bandwidth for server
	// Bandwidth for server
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// (String) Boot mode of server (std, single, cd)
	// Boot mode of server (`std`, `single`, `cd`)
	BootMode *string `json:"bootMode,omitempty" tf:"boot_mode,omitempty"`

	// (Number) Current CPUs count of server
	// Current CPUs count of server
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (String) Current CPU frequency of server
	// Current CPU frequency of server
	CPUFrequency *string `json:"cpuFrequency,omitempty" tf:"cpu_frequency,omitempty"`

	// init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	// Cloud-init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	CloudInit *string `json:"cloudInit,omitempty" tf:"cloud_init,omitempty"`

	// (String) Comment for server
	// Comment for server
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	Configuration []ConfigurationObservation `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (Number) Configurator identifier
	// Configurator identifier
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (List of Object) Current server disks representation (see below for nested schema)
	// Current server disks representation
	Disks []DisksObservation `json:"disks,omitempty" tf:"disks,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// (String) Hostname of the server
	// Hostname of the server
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Image ID for servers (not supported for cloned servers)
	// Image ID for servers (not supported for cloned servers)
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// (Boolean) Flag that shows status of DDoS guard service
	// Flag that shows status of DDoS guard service
	IsDdosGuard *bool `json:"isDdosGuard,omitempty" tf:"is_ddos_guard,omitempty"`

	// (Boolean) Is root password required for server
	// Is root password required for server
	IsRootPasswordRequired *bool `json:"isRootPasswordRequired,omitempty" tf:"is_root_password_required,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for created server (not supported for cloned servers) (see below for nested schema)
	// Flag that enables local network for created server (not supported for cloned servers)
	LocalNetwork []LocalNetworkObservation `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// 1, ru-2, 'ru-3', de-1, kz-1, 'nl-1')
	// Location for the server (`ru-1`, `ru-2`, 'ru-3', `de-1`, `kz-1`, 'nl-1')
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Main IPv4 address from public interface
	// Main IPv4 address from public interface
	MainIPv4 *string `json:"mainIpv4,omitempty" tf:"main_ipv4,omitempty"`

	// (String) Name for server
	// Name for server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of Object) (see below for nested schema)
	Networks []NetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`

	// (List of Object) Information about specified OS (see below for nested schema)
	// Information about specified OS
	Os []OsObservation `json:"os,omitempty" tf:"os,omitempty"`

	// (Number) OS ID for server (not supported for cloned servers)
	// OS ID for server (not supported for cloned servers)
	OsID *float64 `json:"osId,omitempty" tf:"os_id,omitempty"`

	// (Number) Preset ID for server (conflicts with configuration)
	// Preset ID for server (conflicts with configuration)
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created server
	// Project ID for created server
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Current RAM size of server
	// Current RAM size of server
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`

	// (Set of Number) List of SSH keys IDs for server
	// List of SSH keys IDs for server
	// +listType=set
	SSHKeysIds []*float64 `json:"sshKeysIds,omitempty" tf:"ssh_keys_ids,omitempty"`

	// (List of Object) Information about specified software (if software_id was set) (see below for nested schema)
	// Information about specified software (if software_id was set)
	Software []SoftwareObservation `json:"software,omitempty" tf:"software,omitempty"`

	// (Number) Software ID for server (not supported for cloned servers)
	// Software ID for server (not supported for cloned servers)
	SoftwareID *float64 `json:"softwareId,omitempty" tf:"software_id,omitempty"`

	// (Number) Server ID for which clone should be created
	// Server ID for which clone should be created
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// (String) Last boot time (in ISO8601 format)
	// Last boot time (in ISO8601 format)
	StartAt *string `json:"startAt,omitempty" tf:"start_at,omitempty"`

	// (String) Current status of server (installing, software_install, reinstalling, on, off, turning_on, turning_off, hard_turning_off, rebooting, hard_rebooting, removing, removed, cloning, transfer, blocked, configuring, no_paid, permanent_blocked)
	// Current status of server (`installing`, `software_install`, `reinstalling`, `on`, `off`, `turning_on`, `turning_off`, `hard_turning_off`, `rebooting`, `hard_rebooting`, `removing`, `removed`, `cloning`, `transfer`, `blocked`, `configuring`, `no_paid`, `permanent_blocked`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ServerParameters struct {

	// 1, spb-3, 'spb-4', msk-1, nsk-1, 'ams-1', 'fra-1', 'ala-1')
	// Availability zone for server (`spb-1`, `spb-3`, 'spb-4', `msk-1`, `nsk-1`, 'ams-1', 'fra-1', 'ala-1')
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Number) Bandwidth for server
	// Bandwidth for server
	// +kubebuilder:validation:Optional
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	// Cloud-init script. If script requires external network you should use floating_ip_id field instead of twc_floating_ip.resource
	// +kubebuilder:validation:Optional
	CloudInit *string `json:"cloudInit,omitempty" tf:"cloud_init,omitempty"`

	// (String) Comment for server
	// Comment for server
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	// +kubebuilder:validation:Optional
	Configuration []ConfigurationParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Floating IP ID for server
	// Floating IP ID for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/vpc/v1alpha1.FloatingIP
	// +kubebuilder:validation:Optional
	FloatingIPID *string `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.Reference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in vpc to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.Selector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// (String) Hostname of the server
	// Hostname of the server
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) Image ID for servers (not supported for cloned servers)
	// Image ID for servers (not supported for cloned servers)
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// (Boolean) Is root password required for server
	// Is root password required for server
	// +kubebuilder:validation:Optional
	IsRootPasswordRequired *bool `json:"isRootPasswordRequired,omitempty" tf:"is_root_password_required,omitempty"`

	// (Block List, Max: 1) Flag that enables local network for created server (not supported for cloned servers) (see below for nested schema)
	// Flag that enables local network for created server (not supported for cloned servers)
	// +kubebuilder:validation:Optional
	LocalNetwork []LocalNetworkParameters `json:"localNetwork,omitempty" tf:"local_network,omitempty"`

	// (String) Name for server
	// Name for server
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) OS ID for server (not supported for cloned servers)
	// OS ID for server (not supported for cloned servers)
	// +kubebuilder:validation:Optional
	OsID *float64 `json:"osId,omitempty" tf:"os_id,omitempty"`

	// (Number) Preset ID for server (conflicts with configuration)
	// Preset ID for server (conflicts with configuration)
	// +kubebuilder:validation:Optional
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created server
	// Project ID for created server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of Number) List of SSH keys IDs for server
	// List of SSH keys IDs for server
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/ssh/v1alpha1.SSHKey
	// +kubebuilder:validation:Optional
	// +listType=set
	SSHKeysIds []*float64 `json:"sshKeysIds,omitempty" tf:"ssh_keys_ids,omitempty"`

	// References to SSHKey in ssh to populate sshKeysIds.
	// +kubebuilder:validation:Optional
	SSHKeysIdsRefs []v1.Reference `json:"sshKeysIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SSHKey in ssh to populate sshKeysIds.
	// +kubebuilder:validation:Optional
	SSHKeysIdsSelector *v1.Selector `json:"sshKeysIdsSelector,omitempty" tf:"-"`

	// (Number) Software ID for server (not supported for cloned servers)
	// Software ID for server (not supported for cloned servers)
	// +kubebuilder:validation:Optional
	SoftwareID *float64 `json:"softwareId,omitempty" tf:"software_id,omitempty"`

	// (Number) Server ID for which clone should be created
	// Server ID for which clone should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`
}

type SoftwareInitParameters struct {
}

type SoftwareObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name for server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SoftwareParameters struct {
}

// ServerSpec defines the desired state of Server
type ServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerInitParameters `json:"initProvider,omitempty"`
}

// ServerStatus defines the observed state of Server.
type ServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Server is the Schema for the Servers API. Resource for describing needed server and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type Server struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServerSpec   `json:"spec"`
	Status ServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerList contains a list of Servers
type ServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Server `json:"items"`
}

// Repository type metadata.
var (
	Server_Kind             = "Server"
	Server_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Server_Kind}.String()
	Server_KindAPIVersion   = Server_Kind + "." + CRDGroupVersion.String()
	Server_GroupVersionKind = CRDGroupVersion.WithKind(Server_Kind)
)

func init() {
	SchemeBuilder.Register(&Server{}, &ServerList{})
}
