// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ServerIPInitParameters struct {

	// (String) PTR for created IP. Must be valid domain name without trailing dot
	// PTR for created IP. Must be valid domain name without trailing dot
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) Server ID for which IP should be created
	// Server ID for which IP should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`

	// (String) Type for created IP (ipv4, ipv6)
	// Type for created IP (`ipv4`, `ipv6`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServerIPObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Address of created IP
	// Address of created IP
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Boolean) Flag that shows IP is main or not (always false for now)
	// Flag that shows IP is main or not (always `false` for now)
	IsMain *bool `json:"isMain,omitempty" tf:"is_main,omitempty"`

	// (String) PTR for created IP. Must be valid domain name without trailing dot
	// PTR for created IP. Must be valid domain name without trailing dot
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) Server ID for which IP should be created
	// Server ID for which IP should be created
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// (String) Type for created IP (ipv4, ipv6)
	// Type for created IP (`ipv4`, `ipv6`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServerIPParameters struct {

	// (String) PTR for created IP. Must be valid domain name without trailing dot
	// PTR for created IP. Must be valid domain name without trailing dot
	// +kubebuilder:validation:Optional
	Ptr *string `json:"ptr,omitempty" tf:"ptr,omitempty"`

	// (Number) Server ID for which IP should be created
	// Server ID for which IP should be created
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	SourceServerID *float64 `json:"sourceServerId,omitempty" tf:"source_server_id,omitempty"`

	// Reference to a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDRef *v1.Reference `json:"sourceServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate sourceServerId.
	// +kubebuilder:validation:Optional
	SourceServerIDSelector *v1.Selector `json:"sourceServerIdSelector,omitempty" tf:"-"`

	// (String) Type for created IP (ipv4, ipv6)
	// Type for created IP (`ipv4`, `ipv6`)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ServerIPSpec defines the desired state of ServerIP
type ServerIPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerIPInitParameters `json:"initProvider,omitempty"`
}

// ServerIPStatus defines the observed state of ServerIP.
type ServerIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServerIP is the Schema for the ServerIPs API. Resource for describing needed additional IP address for server and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type ServerIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ServerIPSpec   `json:"spec"`
	Status ServerIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerIPList contains a list of ServerIPs
type ServerIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerIP `json:"items"`
}

// Repository type metadata.
var (
	ServerIP_Kind             = "ServerIP"
	ServerIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerIP_Kind}.String()
	ServerIP_KindAPIVersion   = ServerIP_Kind + "." + CRDGroupVersion.String()
	ServerIP_GroupVersionKind = CRDGroupVersion.WithKind(ServerIP_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerIP{}, &ServerIPList{})
}
