apiVersion: k8s.timeweb.m.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/nodegroup
  labels:
    testing.upbound.io/example-name: example-k8s-node-group
  name: example-k8s-node-group
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: twc_k8s_cluster
    name: example-k8s-node-group
    nodeCount: 2
    presetId: ${data.twc_k8s_preset.example-k8s-preset-worker.id}

---

apiVersion: k8s.timeweb.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/nodegroup
  labels:
    testing.upbound.io/example-name: example-k8s-cluster
  name: example-k8s-cluster
  namespace: crossplane-system
spec:
  forProvider:
    description: some example cluster
    highAvailability: false
    ingress: true
    name: example-cluster
    networkDriver: flannel
    presetId: ${data.twc_k8s_preset.example-k8s-preset-master.id}
    version: v1.22.17
