apiVersion: server.timeweb.crossplane.io/v1alpha1
kind: DiskBackupSchedule
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/diskbackupschedule
  labels:
    testing.upbound.io/example-name: main-disk-example
  name: main-disk-example
spec:
  forProvider:
    copyCount: 10
    creationStartAt: "2023-02-02T00:00:00.000Z"
    interval: month
    sourceServerDiskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-server
    sourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-server

---

apiVersion: server.timeweb.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/diskbackupschedule
  labels:
    testing.upbound.io/example-name: example-server
  name: example-server
spec:
  forProvider:
    name: Example server with preset
    osId: ${data.twc_os.example-os.id}
    presetId: ${data.twc_presets.example-preset.id}

---

apiVersion: server.timeweb.crossplane.io/v1alpha1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/diskbackupschedule
  labels:
    testing.upbound.io/example-name: example-additional-disk
  name: example-additional-disk
spec:
  forProvider:
    size: ${1024 * 10}
    sourceServerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-server
