apiVersion: dns.timeweb.m.crossplane.io/v1alpha1
kind: DnsRecord
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/dnsrecord
  labels:
    testing.upbound.io/example-name: example-resource-record
  name: example-resource-record
  namespace: crossplane-system
spec:
  forProvider:
    name: '@'
    type: AAAA
    value: ::1
    zoneId: ${data.twc_dns_zone.example-zone.id}
