//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckInitParameters) DeepCopyInto(out *HealthCheckInitParameters) {
	*out = *in
	if in.Fall != nil {
		in, out := &in.Fall, &out.Fall
		*out = new(float64)
		**out = **in
	}
	if in.Inter != nil {
		in, out := &in.Inter, &out.Inter
		*out = new(float64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Proto != nil {
		in, out := &in.Proto, &out.Proto
		*out = new(string)
		**out = **in
	}
	if in.Rise != nil {
		in, out := &in.Rise, &out.Rise
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckInitParameters.
func (in *HealthCheckInitParameters) DeepCopy() *HealthCheckInitParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckObservation) DeepCopyInto(out *HealthCheckObservation) {
	*out = *in
	if in.Fall != nil {
		in, out := &in.Fall, &out.Fall
		*out = new(float64)
		**out = **in
	}
	if in.Inter != nil {
		in, out := &in.Inter, &out.Inter
		*out = new(float64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Proto != nil {
		in, out := &in.Proto, &out.Proto
		*out = new(string)
		**out = **in
	}
	if in.Rise != nil {
		in, out := &in.Rise, &out.Rise
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckObservation.
func (in *HealthCheckObservation) DeepCopy() *HealthCheckObservation {
	if in == nil {
		return nil
	}
	out := new(HealthCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckParameters) DeepCopyInto(out *HealthCheckParameters) {
	*out = *in
	if in.Fall != nil {
		in, out := &in.Fall, &out.Fall
		*out = new(float64)
		**out = **in
	}
	if in.Inter != nil {
		in, out := &in.Inter, &out.Inter
		*out = new(float64)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Proto != nil {
		in, out := &in.Proto, &out.Proto
		*out = new(string)
		**out = **in
	}
	if in.Rise != nil {
		in, out := &in.Rise, &out.Rise
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckParameters.
func (in *HealthCheckParameters) DeepCopy() *HealthCheckParameters {
	if in == nil {
		return nil
	}
	out := new(HealthCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerInitParameters) DeepCopyInto(out *LoadBalancerInitParameters) {
	*out = *in
	if in.Algo != nil {
		in, out := &in.Algo, &out.Algo
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.ClientTimeout != nil {
		in, out := &in.ClientTimeout, &out.ClientTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.FloatingIPID != nil {
		in, out := &in.FloatingIPID, &out.FloatingIPID
		*out = new(string)
		**out = **in
	}
	if in.FloatingIPIDRef != nil {
		in, out := &in.FloatingIPIDRef, &out.FloatingIPIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FloatingIPIDSelector != nil {
		in, out := &in.FloatingIPIDSelector, &out.FloatingIPIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HttprequestTimeout != nil {
		in, out := &in.HttprequestTimeout, &out.HttprequestTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Ips != nil {
		in, out := &in.Ips, &out.Ips
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsKeepalive != nil {
		in, out := &in.IsKeepalive, &out.IsKeepalive
		*out = new(bool)
		**out = **in
	}
	if in.IsSSL != nil {
		in, out := &in.IsSSL, &out.IsSSL
		*out = new(bool)
		**out = **in
	}
	if in.IsSticky != nil {
		in, out := &in.IsSticky, &out.IsSticky
		*out = new(bool)
		**out = **in
	}
	if in.IsUseProxy != nil {
		in, out := &in.IsUseProxy, &out.IsUseProxy
		*out = new(bool)
		**out = **in
	}
	if in.LocalNetwork != nil {
		in, out := &in.LocalNetwork, &out.LocalNetwork
		*out = make([]LocalNetworkInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Maxconn != nil {
		in, out := &in.Maxconn, &out.Maxconn
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PresetID != nil {
		in, out := &in.PresetID, &out.PresetID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerTimeout != nil {
		in, out := &in.ServerTimeout, &out.ServerTimeout
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerInitParameters.
func (in *LoadBalancerInitParameters) DeepCopy() *LoadBalancerInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerObservation) DeepCopyInto(out *LoadBalancerObservation) {
	*out = *in
	if in.Algo != nil {
		in, out := &in.Algo, &out.Algo
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.ClientTimeout != nil {
		in, out := &in.ClientTimeout, &out.ClientTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.FloatingIPID != nil {
		in, out := &in.FloatingIPID, &out.FloatingIPID
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HttprequestTimeout != nil {
		in, out := &in.HttprequestTimeout, &out.HttprequestTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Ips != nil {
		in, out := &in.Ips, &out.Ips
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsKeepalive != nil {
		in, out := &in.IsKeepalive, &out.IsKeepalive
		*out = new(bool)
		**out = **in
	}
	if in.IsSSL != nil {
		in, out := &in.IsSSL, &out.IsSSL
		*out = new(bool)
		**out = **in
	}
	if in.IsSticky != nil {
		in, out := &in.IsSticky, &out.IsSticky
		*out = new(bool)
		**out = **in
	}
	if in.IsUseProxy != nil {
		in, out := &in.IsUseProxy, &out.IsUseProxy
		*out = new(bool)
		**out = **in
	}
	if in.LocalIP != nil {
		in, out := &in.LocalIP, &out.LocalIP
		*out = new(string)
		**out = **in
	}
	if in.LocalNetwork != nil {
		in, out := &in.LocalNetwork, &out.LocalNetwork
		*out = make([]LocalNetworkObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Maxconn != nil {
		in, out := &in.Maxconn, &out.Maxconn
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PresetID != nil {
		in, out := &in.PresetID, &out.PresetID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(float64)
		**out = **in
	}
	if in.ServerTimeout != nil {
		in, out := &in.ServerTimeout, &out.ServerTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerObservation.
func (in *LoadBalancerObservation) DeepCopy() *LoadBalancerObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerParameters) DeepCopyInto(out *LoadBalancerParameters) {
	*out = *in
	if in.Algo != nil {
		in, out := &in.Algo, &out.Algo
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityZone != nil {
		in, out := &in.AvailabilityZone, &out.AvailabilityZone
		*out = new(string)
		**out = **in
	}
	if in.ClientTimeout != nil {
		in, out := &in.ClientTimeout, &out.ClientTimeout
		*out = new(float64)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(float64)
		**out = **in
	}
	if in.FloatingIPID != nil {
		in, out := &in.FloatingIPID, &out.FloatingIPID
		*out = new(string)
		**out = **in
	}
	if in.FloatingIPIDRef != nil {
		in, out := &in.FloatingIPIDRef, &out.FloatingIPIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.FloatingIPIDSelector != nil {
		in, out := &in.FloatingIPIDSelector, &out.FloatingIPIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = make([]HealthCheckParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HttprequestTimeout != nil {
		in, out := &in.HttprequestTimeout, &out.HttprequestTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Ips != nil {
		in, out := &in.Ips, &out.Ips
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsKeepalive != nil {
		in, out := &in.IsKeepalive, &out.IsKeepalive
		*out = new(bool)
		**out = **in
	}
	if in.IsSSL != nil {
		in, out := &in.IsSSL, &out.IsSSL
		*out = new(bool)
		**out = **in
	}
	if in.IsSticky != nil {
		in, out := &in.IsSticky, &out.IsSticky
		*out = new(bool)
		**out = **in
	}
	if in.IsUseProxy != nil {
		in, out := &in.IsUseProxy, &out.IsUseProxy
		*out = new(bool)
		**out = **in
	}
	if in.LocalNetwork != nil {
		in, out := &in.LocalNetwork, &out.LocalNetwork
		*out = make([]LocalNetworkParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Maxconn != nil {
		in, out := &in.Maxconn, &out.Maxconn
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PresetID != nil {
		in, out := &in.PresetID, &out.PresetID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerTimeout != nil {
		in, out := &in.ServerTimeout, &out.ServerTimeout
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerParameters.
func (in *LoadBalancerParameters) DeepCopy() *LoadBalancerParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRule) DeepCopyInto(out *LoadBalancerRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRule.
func (in *LoadBalancerRule) DeepCopy() *LoadBalancerRule {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleInitParameters) DeepCopyInto(out *LoadBalancerRuleInitParameters) {
	*out = *in
	if in.BalancerPort != nil {
		in, out := &in.BalancerPort, &out.BalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.BalancerProto != nil {
		in, out := &in.BalancerProto, &out.BalancerProto
		*out = new(string)
		**out = **in
	}
	if in.LBID != nil {
		in, out := &in.LBID, &out.LBID
		*out = new(float64)
		**out = **in
	}
	if in.LBIDRef != nil {
		in, out := &in.LBIDRef, &out.LBIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBIDSelector != nil {
		in, out := &in.LBIDSelector, &out.LBIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ServerProto != nil {
		in, out := &in.ServerProto, &out.ServerProto
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleInitParameters.
func (in *LoadBalancerRuleInitParameters) DeepCopy() *LoadBalancerRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleList) DeepCopyInto(out *LoadBalancerRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleList.
func (in *LoadBalancerRuleList) DeepCopy() *LoadBalancerRuleList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleObservation) DeepCopyInto(out *LoadBalancerRuleObservation) {
	*out = *in
	if in.BalancerPort != nil {
		in, out := &in.BalancerPort, &out.BalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.BalancerProto != nil {
		in, out := &in.BalancerProto, &out.BalancerProto
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LBID != nil {
		in, out := &in.LBID, &out.LBID
		*out = new(float64)
		**out = **in
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ServerProto != nil {
		in, out := &in.ServerProto, &out.ServerProto
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleObservation.
func (in *LoadBalancerRuleObservation) DeepCopy() *LoadBalancerRuleObservation {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleParameters) DeepCopyInto(out *LoadBalancerRuleParameters) {
	*out = *in
	if in.BalancerPort != nil {
		in, out := &in.BalancerPort, &out.BalancerPort
		*out = new(float64)
		**out = **in
	}
	if in.BalancerProto != nil {
		in, out := &in.BalancerProto, &out.BalancerProto
		*out = new(string)
		**out = **in
	}
	if in.LBID != nil {
		in, out := &in.LBID, &out.LBID
		*out = new(float64)
		**out = **in
	}
	if in.LBIDRef != nil {
		in, out := &in.LBIDRef, &out.LBIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LBIDSelector != nil {
		in, out := &in.LBIDSelector, &out.LBIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ServerProto != nil {
		in, out := &in.ServerProto, &out.ServerProto
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleParameters.
func (in *LoadBalancerRuleParameters) DeepCopy() *LoadBalancerRuleParameters {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleSpec) DeepCopyInto(out *LoadBalancerRuleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleSpec.
func (in *LoadBalancerRuleSpec) DeepCopy() *LoadBalancerRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRuleStatus) DeepCopyInto(out *LoadBalancerRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRuleStatus.
func (in *LoadBalancerRuleStatus) DeepCopy() *LoadBalancerRuleStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkInitParameters) DeepCopyInto(out *LocalNetworkInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkInitParameters.
func (in *LocalNetworkInitParameters) DeepCopy() *LocalNetworkInitParameters {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkObservation) DeepCopyInto(out *LocalNetworkObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkObservation.
func (in *LocalNetworkObservation) DeepCopy() *LocalNetworkObservation {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNetworkParameters) DeepCopyInto(out *LocalNetworkParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNetworkParameters.
func (in *LocalNetworkParameters) DeepCopy() *LocalNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(LocalNetworkParameters)
	in.DeepCopyInto(out)
	return out
}
