// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BackupScheduleInitParameters struct {

	// Database cluster ID for which database auto backups should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/database/v1alpha1.Cluster
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Maximum stored copy count
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// Creation date for first backup
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Enable auto backups
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Interval between auto backups
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`
}

type BackupScheduleObservation struct {

	// Database cluster ID for which database auto backups should be configured
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Maximum stored copy count
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// Creation date for first backup
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Enable auto backups
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Interval between auto backups
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`
}

type BackupScheduleParameters struct {

	// Database cluster ID for which database auto backups should be configured
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/database/v1alpha1.Cluster
	// +kubebuilder:validation:Optional
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in database to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Maximum stored copy count
	// +kubebuilder:validation:Optional
	CopyCount *float64 `json:"copyCount,omitempty" tf:"copy_count,omitempty"`

	// Creation date for first backup
	// +kubebuilder:validation:Optional
	CreationStartAt *string `json:"creationStartAt,omitempty" tf:"creation_start_at,omitempty"`

	// Day of the week when auto backup should be created. Allowed only for week interval, counting starts from 1 (Monday)
	// +kubebuilder:validation:Optional
	DayOfWeek *float64 `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Enable auto backups
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Interval between auto backups
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`
}

// BackupScheduleSpec defines the desired state of BackupSchedule
type BackupScheduleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BackupScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BackupScheduleInitParameters `json:"initProvider,omitempty"`
}

// BackupScheduleStatus defines the observed state of BackupSchedule.
type BackupScheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BackupScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BackupSchedule is the Schema for the BackupSchedules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type BackupSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.copyCount) || (has(self.initProvider) && has(self.initProvider.copyCount))",message="spec.forProvider.copyCount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.creationStartAt) || (has(self.initProvider) && has(self.initProvider.creationStartAt))",message="spec.forProvider.creationStartAt is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.interval) || (has(self.initProvider) && has(self.initProvider.interval))",message="spec.forProvider.interval is a required parameter"
	Spec   BackupScheduleSpec   `json:"spec"`
	Status BackupScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BackupScheduleList contains a list of BackupSchedules
type BackupScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupSchedule `json:"items"`
}

// Repository type metadata.
var (
	BackupSchedule_Kind             = "BackupSchedule"
	BackupSchedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BackupSchedule_Kind}.String()
	BackupSchedule_KindAPIVersion   = BackupSchedule_Kind + "." + CRDGroupVersion.String()
	BackupSchedule_GroupVersionKind = CRDGroupVersion.WithKind(BackupSchedule_Kind)
)

func init() {
	SchemeBuilder.Register(&BackupSchedule{}, &BackupScheduleList{})
}
