// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterInitParameters struct {

	// (String) Availability zone for database cluster
	// Availability zone for database cluster
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Map of String) Configuration parameters for database cluster
	// Configuration parameters for database cluster
	// +mapType=granular
	ConfigParameters map[string]*string `json:"configParameters,omitempty" tf:"config_parameters,omitempty"`

	// (String) Description for project
	// Description for project
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Hash type for database
	// Hash type for database
	HashType *string `json:"hashType,omitempty" tf:"hash_type,omitempty"`

	// (Boolean) Flag that shows allowability database only by external IP address
	// Flag that shows allowability database only by external IP address
	IsExternalIP *bool `json:"isExternalIp,omitempty" tf:"is_external_ip,omitempty"`

	// (String) Name for database cluster
	// Name for database cluster
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Max: 1) Network for database cluster (see below for nested schema)
	// Network for database cluster
	Network []NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (Number) Preset ID for database cluster
	// Preset ID for database cluster
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for managed resource
	// Project ID for managed resource
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/project/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Number of replication instances
	// Number of replication instances
	Replications *float64 `json:"replications,omitempty" tf:"replications,omitempty"`

	// (String) Type of database cluster
	// Type of database cluster
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClusterObservation struct {

	// (String) Availability zone for database cluster
	// Availability zone for database cluster
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Map of String) Configuration parameters for database cluster
	// Configuration parameters for database cluster
	// +mapType=granular
	ConfigParameters map[string]*string `json:"configParameters,omitempty" tf:"config_parameters,omitempty"`

	// (String) Description for project
	// Description for project
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of Object) Information about database disk stats (see below for nested schema)
	// Information about database disk stats
	DiskStats []DiskStatsObservation `json:"diskStats,omitempty" tf:"disk_stats,omitempty"`

	// (String) Hash type for database
	// Hash type for database
	HashType *string `json:"hashType,omitempty" tf:"hash_type,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag that shows allowability database only by external IP address
	// Flag that shows allowability database only by external IP address
	IsExternalIP *bool `json:"isExternalIp,omitempty" tf:"is_external_ip,omitempty"`

	// 1, ru-2, de-1, kz-1, etc.)
	// Location for the server (`ru-1`, `ru-2`, `de-1`, `kz-1`, etc.)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name for database cluster
	// Name for database cluster
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Max: 1) Network for database cluster (see below for nested schema)
	// Network for database cluster
	Network []NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (List of Object) (see below for nested schema)
	Networks []NetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`

	// (Map of String) Configuration parameters for database cluster
	// Configuration parameters for database cluster
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Number) Listening port for incoming connections
	// Listening port for incoming connections
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) Preset ID for database cluster
	// Preset ID for database cluster
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for managed resource
	// Project ID for managed resource
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Number of replication instances
	// Number of replication instances
	Replications *float64 `json:"replications,omitempty" tf:"replications,omitempty"`

	// (String) Current status of database cluster (started, starting, stopped, no_paid)
	// Current status of database cluster (`started`, `starting`, `stopped`, `no_paid`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Type of database cluster
	// Type of database cluster
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ClusterParameters struct {

	// (String) Availability zone for database cluster
	// Availability zone for database cluster
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (Map of String) Configuration parameters for database cluster
	// Configuration parameters for database cluster
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ConfigParameters map[string]*string `json:"configParameters,omitempty" tf:"config_parameters,omitempty"`

	// (String) Description for project
	// Description for project
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Hash type for database
	// Hash type for database
	// +kubebuilder:validation:Optional
	HashType *string `json:"hashType,omitempty" tf:"hash_type,omitempty"`

	// (Boolean) Flag that shows allowability database only by external IP address
	// Flag that shows allowability database only by external IP address
	// +kubebuilder:validation:Optional
	IsExternalIP *bool `json:"isExternalIp,omitempty" tf:"is_external_ip,omitempty"`

	// (String) Name for database cluster
	// Name for database cluster
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block List, Max: 1) Network for database cluster (see below for nested schema)
	// Network for database cluster
	// +kubebuilder:validation:Optional
	Network []NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (Number) Preset ID for database cluster
	// Preset ID for database cluster
	// +kubebuilder:validation:Optional
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for managed resource
	// Project ID for managed resource
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Number) Number of replication instances
	// Number of replication instances
	// +kubebuilder:validation:Optional
	Replications *float64 `json:"replications,omitempty" tf:"replications,omitempty"`

	// (String) Type of database cluster
	// Type of database cluster
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DiskStatsInitParameters struct {
}

type DiskStatsObservation struct {

	// (Number)
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number)
	Used *float64 `json:"used,omitempty" tf:"used,omitempty"`
}

type DiskStatsParameters struct {
}

type IpsInitParameters struct {
}

type IpsObservation struct {

	// (String)
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) Type of database cluster
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IpsParameters struct {
}

type NetworkInitParameters struct {

	// (String) The ID of this resource.
	// Network ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkObservation struct {

	// (String) The ID of this resource.
	// Network ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworkParameters struct {

	// (String) The ID of this resource.
	// Network ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type NetworksInitParameters struct {
}

type NetworksObservation struct {

	// (List of Object) (see below for nested schema)
	Ips []IpsObservation `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) Type of database cluster
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworksParameters struct {
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. Resource for describing needed database cluster and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.presetId) || (has(self.initProvider) && has(self.initProvider.presetId))",message="spec.forProvider.presetId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
