// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/database/v1alpha1"
	v1alpha1dns "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/dns/v1alpha1"
	v1alpha1firewall "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/firewall/v1alpha1"
	v1alpha1k8s "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/k8s/v1alpha1"
	v1alpha1project "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1"
	v1alpha1s3 "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/s3/v1alpha1"
	v1alpha1server "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/server/v1alpha1"
	v1alpha1ssh "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/ssh/v1alpha1"
	v1alpha1storage "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/storage/v1alpha1"
	v1alpha1cluster "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/v1alpha1"
	v1beta1 "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/v1beta1"
	v1alpha1vpc "github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/vpc/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1k8s.SchemeBuilder.AddToScheme,
		v1alpha1project.SchemeBuilder.AddToScheme,
		v1alpha1s3.SchemeBuilder.AddToScheme,
		v1alpha1server.SchemeBuilder.AddToScheme,
		v1alpha1ssh.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1vpc.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
