// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BucketInitParameters struct {

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	Configuration []ConfigurationInitParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Name for S3 bucket
	// Name for S3 bucket
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	// Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created S3 bucket
	// Project ID for created S3 bucket
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Type for S3 bucket (private, public)
	// Type for S3 bucket (`private`, `public`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BucketObservation struct {

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	Configuration []ConfigurationObservation `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (Number) Configurator identifier
	// Configurator identifier
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (List of Object) Information about storage disk stats (see below for nested schema)
	// Information about storage disk stats
	DiskStats []DiskStatsObservation `json:"diskStats,omitempty" tf:"disk_stats,omitempty"`

	// (String) Full name for S3 bucket (with random prefix)
	// Full name for S3 bucket (with random prefix)
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// compatible clients
	// Hostname for access via S3-compatible clients
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Location of storage
	// Location of storage
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) Name for S3 bucket
	// Name for S3 bucket
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Stored objects amount
	// Stored objects amount
	ObjectAmount *float64 `json:"objectAmount,omitempty" tf:"object_amount,omitempty"`

	// (Number) Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	// Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created S3 bucket
	// Project ID for created S3 bucket
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Current status of S3 bucket (no_paid, created, transfer)
	// Current status of S3 bucket (`no_paid`, `created`, `transfer`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Type for S3 bucket (private, public)
	// Type for S3 bucket (`private`, `public`)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BucketParameters struct {

	// (Block List, Max: 1) Configuration for server (see below for nested schema)
	// Configuration for server
	// +kubebuilder:validation:Optional
	Configuration []ConfigurationParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Name for S3 bucket
	// Name for S3 bucket
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	// Preset ID for S3 bucket. Cannot be used with (conflicts with configuration)
	// +kubebuilder:validation:Optional
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for created S3 bucket
	// Project ID for created S3 bucket
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Type for S3 bucket (private, public)
	// Type for S3 bucket (`private`, `public`)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigurationInitParameters struct {

	// (Number) Configurator identifier
	// Configurator ID for S3 Strorage
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Disk size for S3 Storage
	// Disk size for S3 Storage
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`
}

type ConfigurationObservation struct {

	// (Number) Configurator identifier
	// Configurator ID for S3 Strorage
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Disk size for S3 Storage
	// Disk size for S3 Storage
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`
}

type ConfigurationParameters struct {

	// (Number) Configurator identifier
	// Configurator ID for S3 Strorage
	// +kubebuilder:validation:Optional
	ConfiguratorID *float64 `json:"configuratorId" tf:"configurator_id,omitempty"`

	// (Number) Disk size for S3 Storage
	// Disk size for S3 Storage
	// +kubebuilder:validation:Optional
	Disk *float64 `json:"disk" tf:"disk,omitempty"`
}

type DiskStatsInitParameters struct {
}

type DiskStatsObservation struct {

	// (Number)
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (Number)
	Used *float64 `json:"used,omitempty" tf:"used,omitempty"`
}

type DiskStatsParameters struct {
}

// BucketSpec defines the desired state of Bucket
type BucketSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BucketParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketInitParameters `json:"initProvider,omitempty"`
}

// BucketStatus defines the observed state of Bucket.
type BucketStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Bucket is the Schema for the Buckets API. Resource for describing needed S3 bucket and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,twc}
type Bucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   BucketSpec   `json:"spec"`
	Status BucketStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketList contains a list of Buckets
type BucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bucket `json:"items"`
}

// Repository type metadata.
var (
	Bucket_Kind             = "Bucket"
	Bucket_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Bucket_Kind}.String()
	Bucket_KindAPIVersion   = Bucket_Kind + "." + CRDGroupVersion.String()
	Bucket_GroupVersionKind = CRDGroupVersion.WithKind(Bucket_Kind)
)

func init() {
	SchemeBuilder.Register(&Bucket{}, &BucketList{})
}
