// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterInitParameters struct {

	// (Block List, Max: 1) Configuration for master nodes (see below for nested schema)
	// Configuration for master nodes
	Configuration []ConfigurationInitParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Description for K8S cluster
	// Description for K8S cluster
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) High Availability for K8S cluster
	// High Availability for K8S cluster
	HighAvailability *bool `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// (Boolean) Add ingress for K8S cluster
	// Add ingress for K8S cluster
	Ingress *bool `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Block List) Maintenance window for cluster (see below for nested schema)
	// Maintenance window for cluster
	MaintenanceSlot []MaintenanceSlotInitParameters `json:"maintenanceSlot,omitempty" tf:"maintenance_slot,omitempty"`

	// (String) Name for K8S cluster
	// Name for K8S cluster
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network driver for K8S cluster may be retrieved from API
	// Network driver for K8S cluster [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/network_drivers)
	NetworkDriver *string `json:"networkDriver,omitempty" tf:"network_driver,omitempty"`

	// (String) ID of VPC for K8S cluster
	// ID of VPC for K8S cluster
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/vpc/v1alpha1.VPC
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a VPC in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Block List) OIDC provider settings for cluster (see below for nested schema)
	// OIDC provider settings for cluster
	OidcProvider []OidcProviderInitParameters `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// (Number) Preset ID for nodes in group
	// Preset ID for nodes in group
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for K8S cluster
	// Project ID for K8S cluster
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/project/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) K8S version may be retrieved from API. If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	// K8S version [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/k8s_versions). If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ClusterObservation struct {

	// (Number) Sum of CPU count of all worker nodes
	// Sum of CPU count of all worker nodes
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (Block List, Max: 1) Configuration for master nodes (see below for nested schema)
	// Configuration for master nodes
	Configuration []ConfigurationObservation `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Description for K8S cluster
	// Description for K8S cluster
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Sum of disks volume of worker nodes
	// Sum of disks volume of worker nodes
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`

	// (Boolean) High Availability for K8S cluster
	// High Availability for K8S cluster
	HighAvailability *bool `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Add ingress for K8S cluster
	// Add ingress for K8S cluster
	Ingress *bool `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Block List) Maintenance window for cluster (see below for nested schema)
	// Maintenance window for cluster
	MaintenanceSlot []MaintenanceSlotObservation `json:"maintenanceSlot,omitempty" tf:"maintenance_slot,omitempty"`

	// (String) Name for K8S cluster
	// Name for K8S cluster
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network driver for K8S cluster may be retrieved from API
	// Network driver for K8S cluster [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/network_drivers)
	NetworkDriver *string `json:"networkDriver,omitempty" tf:"network_driver,omitempty"`

	// (String) ID of VPC for K8S cluster
	// ID of VPC for K8S cluster
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (Block List) OIDC provider settings for cluster (see below for nested schema)
	// OIDC provider settings for cluster
	OidcProvider []OidcProviderObservation `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// (Number) Preset ID for nodes in group
	// Preset ID for nodes in group
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for K8S cluster
	// Project ID for K8S cluster
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Sum of RAM count of all worker nodes
	// Sum of RAM count of all worker nodes
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`

	// (String) Current status of K8S cluster (installing, provisioning, active, unpaid, started, not_installed, failed, unpaid_not_installed, deletion)
	// Current status of K8S cluster (`installing`, `provisioning`, `active`, `unpaid`, `started`, `not_installed`, `failed`, `unpaid_not_installed`, `deletion`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) K8S version may be retrieved from API. If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	// K8S version [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/k8s_versions). If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ClusterParameters struct {

	// (Block List, Max: 1) Configuration for master nodes (see below for nested schema)
	// Configuration for master nodes
	// +kubebuilder:validation:Optional
	Configuration []ConfigurationParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// (String) Description for K8S cluster
	// Description for K8S cluster
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) High Availability for K8S cluster
	// High Availability for K8S cluster
	// +kubebuilder:validation:Optional
	HighAvailability *bool `json:"highAvailability,omitempty" tf:"high_availability,omitempty"`

	// (Boolean) Add ingress for K8S cluster
	// Add ingress for K8S cluster
	// +kubebuilder:validation:Optional
	Ingress *bool `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (Block List) Maintenance window for cluster (see below for nested schema)
	// Maintenance window for cluster
	// +kubebuilder:validation:Optional
	MaintenanceSlot []MaintenanceSlotParameters `json:"maintenanceSlot,omitempty" tf:"maintenance_slot,omitempty"`

	// (String) Name for K8S cluster
	// Name for K8S cluster
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network driver for K8S cluster may be retrieved from API
	// Network driver for K8S cluster [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/network_drivers)
	// +kubebuilder:validation:Optional
	NetworkDriver *string `json:"networkDriver,omitempty" tf:"network_driver,omitempty"`

	// (String) ID of VPC for K8S cluster
	// ID of VPC for K8S cluster
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/vpc/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a VPC in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Block List) OIDC provider settings for cluster (see below for nested schema)
	// OIDC provider settings for cluster
	// +kubebuilder:validation:Optional
	OidcProvider []OidcProviderParameters `json:"oidcProvider,omitempty" tf:"oidc_provider,omitempty"`

	// (Number) Preset ID for nodes in group
	// Preset ID for nodes in group
	// +kubebuilder:validation:Optional
	PresetID *float64 `json:"presetId,omitempty" tf:"preset_id,omitempty"`

	// (Number) Project ID for K8S cluster
	// Project ID for K8S cluster
	// +crossplane:generate:reference:type=github.com/lebedevdsl/crossplane-upjet-provider-timeweb/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) K8S version may be retrieved from API. If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	// K8S version [may be retrieved from API](https://api.timeweb.cloud/api/v1/k8s/k8s_versions). If your version is outdated, we will take the latest patch of provided version! You need to check your version after cluster installation!
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ConfigurationInitParameters struct {

	// (Number) Sum of CPU count of all worker nodes
	// CPU count for node group
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (Number) Configurator ID for creating nodes
	// Configurator ID for creating nodes
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Sum of disks volume of worker nodes
	// Disk node group size
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`

	// (Number) Sum of RAM count of all worker nodes
	// RAM node group worker size
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`
}

type ConfigurationObservation struct {

	// (Number) Sum of CPU count of all worker nodes
	// CPU count for node group
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (Number) Configurator ID for creating nodes
	// Configurator ID for creating nodes
	ConfiguratorID *float64 `json:"configuratorId,omitempty" tf:"configurator_id,omitempty"`

	// (Number) Sum of disks volume of worker nodes
	// Disk node group size
	Disk *float64 `json:"disk,omitempty" tf:"disk,omitempty"`

	// (Number) Sum of RAM count of all worker nodes
	// RAM node group worker size
	RAM *float64 `json:"ram,omitempty" tf:"ram,omitempty"`
}

type ConfigurationParameters struct {

	// (Number) Sum of CPU count of all worker nodes
	// CPU count for node group
	// +kubebuilder:validation:Optional
	CPU *float64 `json:"cpu" tf:"cpu,omitempty"`

	// (Number) Configurator ID for creating nodes
	// Configurator ID for creating nodes
	// +kubebuilder:validation:Optional
	ConfiguratorID *float64 `json:"configuratorId" tf:"configurator_id,omitempty"`

	// (Number) Sum of disks volume of worker nodes
	// Disk node group size
	// +kubebuilder:validation:Optional
	Disk *float64 `json:"disk" tf:"disk,omitempty"`

	// (Number) Sum of RAM count of all worker nodes
	// RAM node group worker size
	// +kubebuilder:validation:Optional
	RAM *float64 `json:"ram" tf:"ram,omitempty"`
}

type MaintenanceSlotInitParameters struct {

	// (String) May start from this time (HH:MM format)
	// May start from this time (HH:MM format)
	From *string `json:"from,omitempty" tf:"from,omitempty"`

	// (String) May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	// May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	To *string `json:"to,omitempty" tf:"to,omitempty"`

	// (String) Maintenance slot type
	// Maintenance slot type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MaintenanceSlotObservation struct {

	// (String) May start from this time (HH:MM format)
	// May start from this time (HH:MM format)
	From *string `json:"from,omitempty" tf:"from,omitempty"`

	// (String) May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	// May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	To *string `json:"to,omitempty" tf:"to,omitempty"`

	// (String) Maintenance slot type
	// Maintenance slot type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MaintenanceSlotParameters struct {

	// (String) May start from this time (HH:MM format)
	// May start from this time (HH:MM format)
	// +kubebuilder:validation:Optional
	From *string `json:"from,omitempty" tf:"from,omitempty"`

	// (String) May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	// May end to this time (HH:MM). Notice: The actual duration depends on the number of nodes in the cluster.
	// +kubebuilder:validation:Optional
	To *string `json:"to,omitempty" tf:"to,omitempty"`

	// (String) Maintenance slot type
	// Maintenance slot type
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type OidcProviderInitParameters struct {

	// (String) Unique identifier by authentication server
	// Unique identifier by authentication server
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) OIDC Provider URL
	// OIDC Provider URL
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// (String) Name for K8S cluster
	// Name for OIDC provider setting
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Name of the field in the ID token that the OIDC authentication system uses as the username
	// Name of the field in the ID token that the OIDC authentication system uses as the username
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`
}

type OidcProviderObservation struct {

	// (String) Unique identifier by authentication server
	// Unique identifier by authentication server
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) OIDC Provider URL
	// OIDC Provider URL
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// (String) Name for K8S cluster
	// Name for OIDC provider setting
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Current status of K8S cluster (installing, provisioning, active, unpaid, started, not_installed, failed, unpaid_not_installed, deletion)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Name of the field in the ID token that the OIDC authentication system uses as the username
	// Name of the field in the ID token that the OIDC authentication system uses as the username
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`
}

type OidcProviderParameters struct {

	// (String) Unique identifier by authentication server
	// Unique identifier by authentication server
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) OIDC Provider URL
	// OIDC Provider URL
	// +kubebuilder:validation:Optional
	IssuerURL *string `json:"issuerUrl" tf:"issuer_url,omitempty"`

	// (String) Name for K8S cluster
	// Name for OIDC provider setting
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) Name of the field in the ID token that the OIDC authentication system uses as the username
	// Name of the field in the ID token that the OIDC authentication system uses as the username
	// +kubebuilder:validation:Optional
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. Resource for describing needed K8S cluster and provides actual information about its status
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,twc}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkDriver) || (has(self.initProvider) && has(self.initProvider.networkDriver))",message="spec.forProvider.networkDriver is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
