apiVersion: s3.timeweb.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: example-s3-bucket
  name: example-s3-bucket
  namespace: crossplane-system
spec:
  forProvider:
    name: example-s3-bucket
    presetId: ${data.twc_s3_preset.example-s3-preset.id}
    type: private
